import os
import config
from processors import source_1_cerebro
from processors import source_2_reviews

def main():
    print("🚀 Starting Omni Data Engine...")
    print(f"📂 Output Target: {config.REPORT_FILE}")
    
    report_content = "# Omni Strategy Candidates Report\n"
    report_content += "*Generated by Omni Traffic System*\n\n"
    
    # --- PHASE 1: TRAFFIC (Cerebro) ---
    print("1️⃣ Processing Source 1: Traffic Data...")
    traffic_candidates = source_1_cerebro.process_cerebro_data(config.DATA_SOURCE_1_PATH)
    if traffic_candidates:
        report_content += source_1_cerebro.generate_report_section(traffic_candidates)
        report_content += "---\n\n"
    
    # --- PHASE 2: REVIEWS (Rufus/Happy/Defect) ---
    print("2️⃣ Processing Source 2: Review Data...")
    
    if os.path.exists(config.DATA_SOURCE_2_HAPPY_PATH) and os.path.exists(config.DATA_SOURCE_2_DEFECT_PATH):
        review_strategy = source_2_reviews.process_reviews(
            config.DATA_SOURCE_2_HAPPY_PATH, 
            config.DATA_SOURCE_2_DEFECT_PATH
        )
        report_content += source_2_reviews.generate_report_section(review_strategy)
        print("   ✅ Reviews Processed.")
    else:
        print("⚠️ Review data files not found. Skipping Phase 2.")
        print(f"   Checked: {config.DATA_SOURCE_2_HAPPY_PATH}")

    # --- SAVE REPORT ---
    if not os.path.exists(config.OUTPUT_DIR):
        os.makedirs(config.OUTPUT_DIR)
        
    with open(config.REPORT_FILE, "w", encoding="utf-8") as f:
        f.write(report_content)
    
    print(f"✅ DONE. Full Strategy Report created at: {config.REPORT_FILE}")

if __name__ == "__main__":
    main()