"""Add stores table schema

Revision ID: b38ead6d9b8c
Revises: 01c711975ca4
Create Date: 2025-07-30 16:06:57.716482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b38ead6d9b8c'
down_revision = '01c711975ca4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('shopify_domain', sa.String(length=255), nullable=False, comment='Shopify store domain (e.g., example.myshopify.com)'),
        sa.Column('shopify_access_token', sa.Text(), nullable=False, comment='Encrypted Shopify access token for API calls'),
        sa.Column('store_name', sa.String(length=255), nullable=False, comment='Display name of the Shopify store'),
        sa.Column('owner_email', sa.String(length=255), nullable=False, comment='Email address of the store owner'),
        sa.Column('plan_name', sa.String(length=100), nullable=True, comment='Shopify plan name (Basic, Shopify, Advanced, Plus)'),
        sa.Column('timezone', sa.String(length=100), nullable=True, comment='Store timezone'),
        sa.Column('currency', sa.String(length=10), nullable=True, comment='Store primary currency code'),
        sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last successful data synchronization'),
        sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the store is active and should be processed'),
        sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Store-specific settings and configuration'),
        sa.Column('product_count', sa.Integer(), nullable=False, comment='Cached count of products in the store'),
        sa.Column('last_analysis_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last SEO analysis'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('shopify_domain')
    )
    op.create_index(op.f('ix_stores_created_at'), 'stores', ['created_at'], unique=False)
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_is_active'), 'stores', ['is_active'], unique=False)
    op.create_index(op.f('ix_stores_owner_email'), 'stores', ['owner_email'], unique=False)
    op.create_index(op.f('ix_stores_shopify_domain'), 'stores', ['shopify_domain'], unique=False)
    op.create_index(op.f('ix_stores_updated_at'), 'stores', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_updated_at'), table_name='stores')
    op.drop_index(op.f('ix_stores_shopify_domain'), table_name='stores')
    op.drop_index(op.f('ix_stores_owner_email'), table_name='stores')
    op.drop_index(op.f('ix_stores_is_active'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_created_at'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###