"""Create SEO analysis and keyword tables

Revision ID: 189b6c8ed0ca
Revises: 4f72d3180af7
Create Date: 2025-08-07 12:47:39.761778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '189b6c8ed0ca'
down_revision = '4f72d3180af7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create keywords table
    op.create_table('keywords',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('keyword', sa.Text(), nullable=False, comment='The keyword phrase'),
        sa.Column('search_volume', sa.Integer(), nullable=True, comment='Monthly search volume'),
        sa.Column('keyword_difficulty', sa.Integer(), nullable=True, comment='Keyword difficulty score (0-100)'),
        sa.Column('cpc', sa.Numeric(precision=10, scale=2), nullable=True, comment='Cost per click in USD'),
        sa.Column('competition_level', sa.String(length=20), nullable=True, comment='Competition level (low, medium, high)'),
        sa.Column('search_intent', sa.String(length=50), nullable=True, comment='Search intent (informational, navigational, commercial, transactional)'),
        sa.Column('category', sa.String(length=100), nullable=True, comment='Keyword category or topic'),
        sa.Column('source', sa.String(length=50), nullable=False, comment='Source of keyword data (amazon, google, manual, etc.)'),
        sa.Column('trend_score', sa.Integer(), nullable=True, comment='Trend score indicating if keyword is trending up/down'),
        sa.Column('seasonal_pattern', sa.String(length=100), nullable=True, comment='Seasonal pattern description'),
        sa.PrimaryKeyConstraint('id'),
        comment='Keywords for SEO research and optimization'
    )
    op.create_index(op.f('ix_keywords_category'), 'keywords', ['category'], unique=False)
    op.create_index(op.f('ix_keywords_created_at'), 'keywords', ['created_at'], unique=False)
    op.create_index(op.f('ix_keywords_id'), 'keywords', ['id'], unique=False)
    op.create_index(op.f('ix_keywords_keyword'), 'keywords', ['keyword'], unique=False)
    op.create_index(op.f('ix_keywords_source'), 'keywords', ['source'], unique=False)
    op.create_index(op.f('ix_keywords_updated_at'), 'keywords', ['updated_at'], unique=False)
    op.create_index('ix_keywords_keyword_source', 'keywords', ['keyword', 'source'], unique=True)
    
    # Create seo_analyses table
    op.create_table('seo_analyses',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('store_id', sa.UUID(), nullable=False, comment='Reference to the store this analysis belongs to'),
        sa.Column('product_id', sa.UUID(), nullable=True, comment='Reference to the product (null for site-wide analysis)'),
        sa.Column('analysis_type', sa.Enum('PRODUCT', 'PAGE', 'SITE', 'TECHNICAL', 'CONTENT', 'KEYWORD', name='analysistype'), nullable=False, comment='Type of SEO analysis performed'),
        sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='analysisstatus'), nullable=False, comment='Current status of the analysis'),
        sa.Column('url', sa.String(length=500), nullable=True, comment='URL that was analyzed (if applicable)'),
        sa.Column('seo_score', sa.Integer(), nullable=True, comment='Overall SEO score (0-100)'),
        sa.Column('title_score', sa.Integer(), nullable=True, comment='Title optimization score (0-100)'),
        sa.Column('description_score', sa.Integer(), nullable=True, comment='Meta description score (0-100)'),
        sa.Column('content_score', sa.Integer(), nullable=True, comment='Content quality score (0-100)'),
        sa.Column('technical_score', sa.Integer(), nullable=True, comment='Technical SEO score (0-100)'),
        sa.Column('keyword_score', sa.Integer(), nullable=True, comment='Keyword optimization score (0-100)'),
        sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of SEO issues found'),
        sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of SEO recommendations'),
        sa.Column('technical_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Technical SEO metrics (page speed, mobile-friendly, etc.)'),
        sa.Column('content_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Content analysis metrics (word count, readability, etc.)'),
        sa.Column('keyword_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Keyword analysis metrics (density, relevance, etc.)'),
        sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the analysis was performed'),
        sa.Column('analysis_duration', sa.Integer(), nullable=True, comment='Analysis duration in seconds'),
        sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if analysis failed'),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        comment='SEO Analysis results and recommendations'
    )
    op.create_index(op.f('ix_seo_analyses_analysis_type'), 'seo_analyses', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_seo_analyses_created_at'), 'seo_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_seo_analyses_id'), 'seo_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_seo_analyses_product_id'), 'seo_analyses', ['product_id'], unique=False)
    op.create_index(op.f('ix_seo_analyses_status'), 'seo_analyses', ['status'], unique=False)
    op.create_index(op.f('ix_seo_analyses_store_id'), 'seo_analyses', ['store_id'], unique=False)
    op.create_index(op.f('ix_seo_analyses_updated_at'), 'seo_analyses', ['updated_at'], unique=False)
    
    # Create product_keywords table
    op.create_table('product_keywords',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('product_id', sa.UUID(), nullable=False, comment='Reference to the product'),
        sa.Column('keyword_id', sa.UUID(), nullable=False, comment='Reference to the keyword'),
        sa.Column('relevance_score', sa.Numeric(precision=3, scale=2), nullable=False, comment='Relevance score between product and keyword (0.00 to 1.00)'),
        sa.Column('current_ranking', sa.Integer(), nullable=True, comment='Current search ranking position for this keyword'),
        sa.Column('target_ranking', sa.Integer(), nullable=True, comment='Target ranking position for this keyword'),
        sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Whether this is a primary keyword for the product'),
        sa.Column('last_ranking_check', sa.DateTime(timezone=True), nullable=True, comment='When ranking was last checked'),
        sa.Column('ranking_history', sa.Text(), nullable=True, comment='JSON string of ranking history'),
        sa.Column('clicks', sa.Integer(), nullable=False, comment='Number of clicks from this keyword'),
        sa.Column('impressions', sa.Integer(), nullable=False, comment='Number of impressions for this keyword'),
        sa.Column('conversions', sa.Integer(), nullable=False, comment='Number of conversions from this keyword'),
        sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        comment='Product-Keyword relationships with performance tracking'
    )
    op.create_index(op.f('ix_product_keywords_created_at'), 'product_keywords', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_keywords_id'), 'product_keywords', ['id'], unique=False)
    op.create_index(op.f('ix_product_keywords_keyword_id'), 'product_keywords', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_product_keywords_product_id'), 'product_keywords', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_keywords_updated_at'), 'product_keywords', ['updated_at'], unique=False)
    op.create_index('ix_product_keywords_product_keyword', 'product_keywords', ['product_id', 'keyword_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_keywords_product_keyword', table_name='product_keywords')
    op.drop_index(op.f('ix_product_keywords_updated_at'), table_name='product_keywords')
    op.drop_index(op.f('ix_product_keywords_product_id'), table_name='product_keywords')
    op.drop_index(op.f('ix_product_keywords_keyword_id'), table_name='product_keywords')
    op.drop_index(op.f('ix_product_keywords_id'), table_name='product_keywords')
    op.drop_index(op.f('ix_product_keywords_created_at'), table_name='product_keywords')
    op.drop_table('product_keywords')
    
    op.drop_index(op.f('ix_seo_analyses_updated_at'), table_name='seo_analyses')
    op.drop_index(op.f('ix_seo_analyses_store_id'), table_name='seo_analyses')
    op.drop_index(op.f('ix_seo_analyses_status'), table_name='seo_analyses')
    op.drop_index(op.f('ix_seo_analyses_product_id'), table_name='seo_analyses')
    op.drop_index(op.f('ix_seo_analyses_id'), table_name='seo_analyses')
    op.drop_index(op.f('ix_seo_analyses_created_at'), table_name='seo_analyses')
    op.drop_index(op.f('ix_seo_analyses_analysis_type'), table_name='seo_analyses')
    op.drop_table('seo_analyses')
    
    op.drop_index('ix_keywords_keyword_source', table_name='keywords')
    op.drop_index(op.f('ix_keywords_updated_at'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_source'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_keyword'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_created_at'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_category'), table_name='keywords')
    op.drop_table('keywords')
    
    # Drop enums
    op.execute('DROP TYPE IF EXISTS analysisstatus')
    op.execute('DROP TYPE IF EXISTS analysistype')
    # ### end Alembic commands ###