"""Create products table

Revision ID: 4f72d3180af7
Revises: b38ead6d9b8c
Create Date: 2025-08-06 12:41:52.378077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '4f72d3180af7'
down_revision = 'b38ead6d9b8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('store_id', sa.UUID(), nullable=False, comment='Reference to the store this product belongs to'),
        sa.Column('shopify_product_id', sa.Integer(), nullable=False, comment='Shopify product ID from the API'),
        sa.Column('title', sa.String(length=500), nullable=False, comment='Product title'),
        sa.Column('handle', sa.String(length=255), nullable=False, comment='Product handle (URL slug)'),
        sa.Column('description', sa.Text(), nullable=True, comment='Product description (HTML)'),
        sa.Column('product_type', sa.String(length=255), nullable=True, comment='Product type/category'),
        sa.Column('vendor', sa.String(length=255), nullable=True, comment='Product vendor/brand'),
        sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False, comment='Product tags array'),
        sa.Column('status', sa.String(length=50), nullable=False, comment='Product status (active, draft, archived)'),
        sa.Column('seo_title', sa.String(length=70), nullable=True, comment='SEO meta title (max 70 chars recommended)'),
        sa.Column('seo_description', sa.String(length=160), nullable=True, comment='SEO meta description (max 160 chars recommended)'),
        sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Product images array with URLs and metadata'),
        sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Product variants with pricing and inventory data'),
        sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='When the product was published'),
        sa.Column('current_seo_score', sa.Integer(), nullable=True, comment='Current SEO score (0-100)'),
        sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True, comment='When SEO analysis was last performed'),
        sa.Column('view_count', sa.Integer(), nullable=False, comment='Cached view count'),
        sa.Column('conversion_rate', sa.Numeric(precision=5, scale=4), nullable=True, comment='Product conversion rate (0.0000 to 1.0000)'),
        sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        comment='Products from Shopify stores with SEO analysis data'
    )
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_handle'), 'products', ['handle'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_product_type'), 'products', ['product_type'], unique=False)
    op.create_index(op.f('ix_products_shopify_product_id'), 'products', ['shopify_product_id'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_index(op.f('ix_products_store_id'), 'products', ['store_id'], unique=False)
    op.create_index(op.f('ix_products_title'), 'products', ['title'], unique=False)
    op.create_index(op.f('ix_products_updated_at'), 'products', ['updated_at'], unique=False)
    op.create_index(op.f('ix_products_vendor'), 'products', ['vendor'], unique=False)
    
    # Create unique constraint on store_id and shopify_product_id
    op.create_unique_constraint('uq_products_store_shopify_id', 'products', ['store_id', 'shopify_product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_products_store_shopify_id', 'products', type_='unique')
    op.drop_index(op.f('ix_products_vendor'), table_name='products')
    op.drop_index(op.f('ix_products_updated_at'), table_name='products')
    op.drop_index(op.f('ix_products_title'), table_name='products')
    op.drop_index(op.f('ix_products_store_id'), table_name='products')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_shopify_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_product_type'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_handle'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###